### PR TITLE
Fix #67: Support for iTunes `summary`, `subtitle` and `keywords` fields

### LINKED ISSUE #67: Add support for itunes:summary field in items
Take a look at the [feed](http://insidejava.libsyn.com/rss) of Inside Java podcast:

```xml
<item>
    <title>#12 - “jpackage” with Kevin Rushforth</title>
    <itunes:title>“jpackage” with Kevin Rushforth</itunes:title>
    <pubDate>Thu, 11 Feb 2021 11:57:06 +0000</pubDate>
    <guid isPermaLink="false"><![CDATA[c0cdd551-0fc0-4eaa-bccf-e43360ed04a9]]></guid>
    <link><![CDATA[https://inside.java/2021/02/11/podcast-012/]]></link>
    <itunes:image href="http://static.libsyn.com/p/assets/f/8/0/a/f80a626bd25156f4/Inside_Java_Apple_Podcast_3000_tile.png" />
    <description><![CDATA[…]]></description>
    <content:encoded><![CDATA[…]]></content:encoded>
    <enclosure length="20706817" type="audio/mpeg" url="http://traffic.libsyn.com/insidejava/InsideJava-Ep012.mp3?dest-id=2318780" />
    <itunes:duration>25:07</itunes:duration>
    <itunes:explicit>clean</itunes:explicit>
    <itunes:keywords>distribution,packaging,jdk,openjdk,jdk16</itunes:keywords>
    <itunes:subtitle><![CDATA[…]]></itunes:subtitle>
    <itunes:summary>…</itunes:summary>
    <itunes:season>1</itunes:season>
    <itunes:episode>12</itunes:episode>
    <itunes:episodeType>full</itunes:episodeType>
    <itunes:author>David Delabassee, Kevin Rushforth</itunes:author>
</item>
```

They use HTML markup for descriptions, but they have the same text in `itunes:summary` and `itunes:subtitle`, but without any tags. It would be really great to support them.

### PR DESCRIPTION
**Pull request by madhead**

### CODE REVIEW

**Review by ivanisidrowu — APPROVED** [review]
Looks good to me. 👍

**Comment by madhead** [comment]
@ivanisidrowu, thank you!

**Review by lush-life — APPROVED** [review]

**Review by AmyPlace — APPROVED** [review]

**Comment by madhead** [comment]
Will you release it soon?

**Comment by ivanisidrowu** [comment]
> Will you release it soon?

We can release v2.1.1 if you need it. :)

**Comment by madhead** [comment]
> > Will you release it soon?
> 
> We can release v2.1.1 if you need it. :)

It would be great!

**Comment by madhead** [comment]
Thank you for the release!

**Pull request merged**
