### PR TITLE
Add ksp processor base and udpate gradle scripts.

### PR DESCRIPTION
**Pull request by ivanisidrowu**
* Update Gradle Versions.
* Update Kotlin from 1.5 to 1.5.30.
* Add KSP processor and provider but valid implementation not yet implemented.

TODO:
* Implement KSP processors and generators.
* Remove KAPT.

### CODE REVIEW

**Comment by dev-weiqi** [comment]
Have you consider using the latest ksp version (1.6.10-1.0.2) ?

**Comment by ivanisidrowu** [comment]
> Have you consider using the latest ksp version (1.6.10-1.0.2) ?

Yeah, thanks, let me try to update it.

**Comment by ivanisidrowu** [comment]
Hi @dev-weiqi , I updated Kotlin to 1.6.10 and KSP to "1.6.10-1.0.2". Please check it out. 👍

**Review by AmyPlace — APPROVED** [review]
LGTM  👍👍👍

**Review by dev-weiqi — APPROVED** [review]

**Review by lush-life — APPROVED** [review]

**Review by lush-life — APPROVED** [review]

**Review by lush-life — APPROVED** [review]

**Pull request merged**
