### PR TITLE
Try to fix Jitpack build failed with duplicate BuildConfig.dex

### PR DESCRIPTION
**Pull request by dev-weiqi**
- Seems like there are two duplicate module paths leading to duplicate BuildConfigs.   
#87 
- Migrate to ViewBinding

### CODE REVIEW

**Comment by dev-weiqi** [comment]
Correct the wrong artifactId! 
Thanks to @ivanisidrowu   🙏

**Review by ivanisidrowu — APPROVED** [review]
Good work, thank you!

**Review by AmyPlace — APPROVED** [review]
👍👍👍

**Review by zoey-yang — APPROVED** [review]
✔️

**Review by lush-life — APPROVED** [review]
✔️

**Pull request merged**
